apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: d0zmuw9hc-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-d1345248f6.1r9a.p3.openshiftapps.com/rhtap/rhtap-qe:4d1ffa145a6789d6e5ece4c567248f97bdddf525@sha256:557c135382a6d690f71ad6fafad6f3644370319199a7e458f953a7a7c9faef0e
          name: container-image
